name: Test Python Package from Nexus

on:
  push:
    branches:
      - implements

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies from Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          pip install pollo \
            --index-url https://$NEXUS_USERNAME:$NEXUS_PASSWORD@54.165.247.238:8081/repository/pollo/simple/ \
            --trusted-host http://54.165.247.238:8081/
