name: Build and Publish python Package to Nexus
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build & twine
        run: |
          pip install --upgrade build twine

      - name: Build package
        run: |
          python -m build

      - name: List build output
        run: |
          ls -la
          ls -la dist/

      - name: upload package to nexus PyPI
        env:
          TWINE_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          twine upload --repository-url "${{ secrets.NEXUS_URL }}" dist/*.tar.gz dist/*.whl
