name: Build and Publish Python Package to Nexus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          pip install --upgrade build twine

      - name: Build the package
        run: |
          python -m build

      - name: Show build output
        run: |
          ls -la dist/

      - name: Upload package to Nexus PyPI
        env:
          TWINE_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          twine upload \
            --repository-url "${{ secrets.NEXUS_URL }}" \
            dist/*.tar.gz dist/*.whl
